services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    env_file:
      - ./.env.development.local
    volumes:
      - ./src:/usr/src/movies-app/server/src
    depends_on:
      database:
        condition: service_healthy
        restart: true

  database:
    image: mysql
    container_name: mysqldb
    ports:
      - 3307:3307
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nestjs
      - MYSQL_TCP_PORT=3307