FROM node:18.20.2-alpine

WORKDIR /usr/src/movies-app/server

COPY package.json .

RUN npm install

RUN npm i -g @nestjs/cli

COPY . .

RUN npm run build

RUN rm -rf ./src

EXPOSE 3001

CMD [ "npm", "run", "start:prod" ]