services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nestjs_api
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NODE_ENV=production
    env_file:
      - ./.env.production.local
    volumes:
      - ./src:/usr/src/movies-app/server/src