---
name: Node.js CI

on: 
  push: 
    branches:
      - master
      - develop
  pull_request: 
    brancher:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd ./server && rm -rf node_modules && npm install
      - run: cd ./server && npm run build && npm run test
      - run: cd ./web && rm -rf node_modules && npm install
      - run: cd ./web && npm run build && npm run test