---
name: Node.js CI

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Run install, build, test
        run: |
          cd server
          sudo rm -rf node_modules
          npm install
          npm config set user 0
          npm config set unsafe-perm true
          npm i -g @nestjs/cli
          npm run build
          npm run test
