FROM node:18.20.2-alpine as build

WORKDIR /usr/src/movies-app/web

COPY . .

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/movies-app/web/dist/web/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY mime.types /etc/nginx/mime.types

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]